[tool]
[tool.poetry]
name = "TeleUserbot_Deployer"
version = "1.0"
description = "Automatic Deploy TeleUserBot to Heroku"
authors = ["SiriDev"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
